#!/bin/bash
# Easy script to create docker

NAME=$1
REPO=$2
PORT=$3

if [[ $# -eq 4 ]]; then
  BRANCH=$4
else
  echo "Getting current branch from current directory"
  BRANCH=$(git rev-parse --abbrev-ref HEAD)
fi

if [[ $# -eq 3 ]]; then
  echo "Creating container $NAME from $REPO/$BRANCH exposing :$PORT"
  echo ""
else
  echo "Usage: "
  echo "       dockerize <:name> <:repo> <:port> (optional) <:branch>"
  echo "Fourth optional parameter: <:branch>"
  exit 1
fi

docker run -d \
  --name=$NAME \
  --restart=always \
  -e repo=$REPO \
  -p $PORT:8080 \
  -e branch=$BRANCH \
  jordond/basesite