#!/bin/bash
# Easy script to create docker

NAME=$1
REPO=$2
PORT=$3
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ $# -ne 3 ]]; then
  echo "Usage: "
  echo "       dockerize <:name> <:repo> <:port> (optional) <:branch>"
  echo "Fourth optional parameter: <:branch>"
  exit 1
fi

if [[ $# -eq 4 ]]; then
  BRANCH=$4
fi

echo "Creating container $NAME from $REPO/$BRANCH exposing :$PORT \n"

docker run -d \
  --name=$NAME \
  --restart=always \
  -e repo=$REPO \
  -p $PORT:8080 \
  -e branch=$BRANCH \
  jordond/basesite